return {
	PlaceObj("ModItemOptionToggle", {
		"name", "Enabled",
		"DisplayName", Untranslated("Enable lottery"),
		"Help", Untranslated("Master switch. Off = the mod does nothing."),
		"DefaultValue", true,
	}),
	PlaceObj("ModItemOptionNumber", {
		"name", "ColonistsPerPercent",
		"DisplayName", Untranslated("Colonists per +1% chance"),
		"Help", Untranslated("How many living colonists add +1% lottery chance. Default 20: 20 people = 1%, 2000 people = 100% (one success per Sol)."),
		"DefaultValue", 20,
		"MinValue", 1,
		"MaxValue", 500,
	}),
	PlaceObj("ModItemOptionNumber", {
		"name", "ChancePerGroup",
		"DisplayName", Untranslated("Chance % per group"),
		"Help", Untranslated("Percent added by each colonist-group. Default 1. Raise this if you want the lottery to fire with fewer people."),
		"DefaultValue", 1,
		"MinValue", 1,
		"MaxValue", 50,
	}),
	PlaceObj("ModItemOptionNumber", {
		"name", "TechsPerSuccess",
		"DisplayName", Untranslated("Techs unlocked per success"),
		"Help", Untranslated("How many technologies to instantly research each time the lottery succeeds. Default 1. At 2000 colonists (100%) this is how many techs you get per Sol."),
		"DefaultValue", 1,
		"MinValue", 1,
		"MaxValue", 20,
	}),
	PlaceObj("ModItemOptionNumber", {
		"name", "MaxRollsPerTick",
		"DisplayName", Untranslated("Max techs per interval"),
		"Help", Untranslated("Hard cap per Sol (or Hour). Extra chance over 100% wants more techs; this stops a megacolony from dumping the whole tree at once. Default 5."),
		"DefaultValue", 5,
		"MinValue", 1,
		"MaxValue", 50,
	}),
	PlaceObj("ModItemOptionChoice", {
		"name", "Interval",
		"DisplayName", Untranslated("Roll interval"),
		"Help", Untranslated("Sol = once per Martian day (recommended). Hour = much faster, for all-tech sandbox runs."),
		"DefaultValue", "Sol",
		"ChoiceList", { "Sol", "Hour" },
	}),
	PlaceObj("ModItemOptionToggle", {
		"name", "UnlockLockedTechs",
		"DisplayName", Untranslated("Also roll locked techs"),
		"Help", Untranslated("Off (default): only techs already unlocked/discovered. On: may discover AND research locked techs — the all-tech playstyle."),
		"DefaultValue", false,
	}),
	PlaceObj("ModItemOptionToggle", {
		"name", "IncludeBreakthroughs",
		"DisplayName", Untranslated("Include Breakthroughs"),
		"Help", Untranslated("Off by default so Breakthroughs stay rare. Turn on for sandbox / all-tech runs."),
		"DefaultValue", false,
	}),
	PlaceObj("ModItemOptionToggle", {
		"name", "ShowNotifications",
		"DisplayName", Untranslated("Show grant notifications"),
		"Help", Untranslated("On-screen text when the lottery grants techs. Safe in debug mode (no vanilla Research Complete toast)."),
		"DefaultValue", true,
	}),
	PlaceObj("ModItemOptionToggle", {
		"name", "LogToConsole",
		"DisplayName", Untranslated("Log rolls to console"),
		"Help", Untranslated("Print [PopTechLottery] lines for misses, grants, and empty pools. Useful if nothing seems to happen."),
		"DefaultValue", true,
	}),
	PlaceObj("ModItemCode", {
		"name", "Script",
		"CodeFileName", "Code/Script.lua",
	}),
}
